services:
  - type: web
    name: vimal-agency
    env: docker
    rootDir: Vimal_Agency
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
