services:
  - type: web
    name: vimal-agency
    env: docker
    rootDir: Vimal_Agency
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        sync: false
      - key: SUPABASE_DB_NAME
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_DB_SSL
        value: require
